import type { getTranslator, MessageKey } from "@/i18n";

type T = Awaited<ReturnType<typeof getTranslator>>["t"];

const KEYS = [
  "weCharge",
  "weChargeHint",
  "weReceived",
  "weReceivedHint",
  "from",
  "to",
  "findParty",
  "chooseParty",
  "partyCOMPANY",
  "partyCLIENT",
  "partyAGENT",
  "partyCONSTRUCTOR",
  "partyTEAM",
  "partyOTHER",
  "partyName",
  "partyEmail",
  "partyAddress",
  "partyNoEmail",
  "sentTo",
  "otherPlaceholder",
  "descriptionExample",
  "ourNumber",
  "numberedByCrm",
  "vatRate",
  "lockedNote",
  "issueAndSend",
  "saveAndSend",
  "category",
  "reference",
  "referenceHint",
  "description",
  "issued",
  "due",
  "dueHint",
  "net",
  "vat",
  "total",
  "lineTotal",
  "project",
  "noProject",
  "chooseProject",
  "noPartyFound",
  "feesTitle",
  "feesHint",
  "linesTitle",
  "lineWords",
  "lineWordsHint",
  "addLine",
  "removeLine",
  "theirInvoice",
  "theirInvoiceNote",
] as const;

/** The words on the company invoice form, in one place for both pages. */
export function invoiceLabels(t: T): Record<string, string> {
  return {
    ...Object.fromEntries(KEYS.map((key) => [key, t(`invoices.${key}` as MessageKey)])),
    notes: t("common.notes"),
    save: t("common.save"),
    cancel: t("common.cancel"),
  };
}
